### ISSUE TITLE
在trian的时候报错：    import realesrgan.archs ModuleNotFoundError: No module named 'realesrgan'

### ISSUE THREAD

**Issue by successhaha** [xinntao/Real-ESRGAN#136]
python realesrgan/train.py -opt options/train_realesrgan_x4plus.yml --auto_resume
Traceback (most recent call last):
  File "realesrgan/train.py", line 8, in <module>
    import realesrgan.archs
ModuleNotFoundError: No module named 'realesrgan'
麻烦您回复下

**Comment by 610821216** [comment]
我也有同樣的問題 我很確定我環境都安裝了

**Comment by edstoica** [comment]
hello,
I have that same issue.
after running
`python realesrgan/train.py -opt options/train_realesrgan_x4plus.yml --auto_resume`

i get
`Traceback (most recent call last):
File "realesrgan/train.py", line 8, in
import realesrgan.archs
ModuleNotFoundError: No module named 'realesrgan'`

I installed all requirements as mentioned above.
system is windows with anaconda and pytorch.

anything I can do about that?

**Comment by edstoica** [comment]
I had to run 
`python setup.py develop `
as a single command again, then it worked.
