### ISSUE TITLE
AttributeError when using anime_6B model

### ISSUE THREAD

**Issue by KeygenLLC** [xinntao/Real-ESRGAN#157]
I'm getting this error on macOS Big Sur when using the anime model. In this test I was testing a fairly compressed jpg from an old anime series.

`go.py` is just my modified script and is basically the same as `inference_realesrgan.py`, but uses `datetime`, `colorama`, and some shorthand args.

```bash
Traceback (most recent call last):
  File "go.py", line 149, in <module>
    main()
  File "go.py", line 115, in main
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'
```

I still get an output file that looks pretty good. Not sure why the error is popping up though.

**Comment by KeygenLLC** [comment]
Figured it out.

If you have a sub-folder in your input folder it will throw this error. It must try to import the folder for some reason. Removing the folder will get rid of the error.

**Comment by LexKoin** [comment]
still happening

**Comment by AIhasArrived** [comment]
@LexKoin  any solution?
