### ISSUE TITLE
can i change patch size?

### ISSUE THREAD

**Issue by lee040118** [xinntao/Real-ESRGAN#172]
### Finetune Real-ESRGAN on my own dataset

I got an error for patch size!!

my hr data set occurred in the process of under-scale conversion to lr data.

**Can I change it to below 64?**

~~~
Traceback (most recent call last):
  File "realesrgan/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/usr/local/lib/python3.7/dist-packages/basicsr/train.py", line 197, in train_pipeline
    train_data = prefetcher.next()
  File "/usr/local/lib/python3.7/dist-packages/basicsr/data/prefetch_dataloader.py", line 76, in next
    return next(self.loader)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/Real-ESRGAN/realesrgan/data/realesrgan_paired_dataset.py", line 94, in __getitem__
    img_gt, img_lq = paired_random_crop(img_gt, img_lq, gt_size, scale, gt_path)
  File "/usr/local/lib/python3.7/dist-packages/basicsr/data/transforms.py", line 67, in paired_random_crop
    raise ValueError(f'LQ ({h_lq}, {w_lq}) is smaller than patch size '
ValueError: LQ (60, 107) is smaller than patch size (64, 64).
~~~

**Comment by cliffordkleinsr** [comment]
Delete the images with a widtth/ height lower than 64 pixels X 64 pixels
