### ISSUE TITLE
Unable to run -- Python Import Error

### ISSUE THREAD

**Issue by geeknik** [xinntao/Real-ESRGAN#185]
Hello, your software was working okay until I did a git pull and grabbed all of the recent changes. Now when I run `python inference_realesrgan.py -n RealESRGAN_x4plus -i image.png`, I get this Python Import Error: 

```
Traceback (most recent call last):
  File "/opt/Real-ESRGAN/inference_realesrgan.py", line 7, in <module>
    from realesrgan import RealESRGANer
  File "/opt/Real-ESRGAN/realesrgan/__init__.py", line 5, in <module>
    from .utils import *
  File "/opt/Real-ESRGAN/realesrgan/utils.py", line 8, in <module>
    from basicsr.utils.download_util import load_file_from_url
ImportError: cannot import name 'load_file_from_url' from 'basicsr.utils.download_util' (/home/geeknik/.local/lib/python3.9/site-packages/basicsr/utils/download_util.py)
```

Running Python 3.9.7 on Fedora with `basicsr in /usr/local/lib/python3.9/site-packages (1.3.4.9)`.

**Comment by geeknik** [comment]
Fixed by forced copying new basicsr files over old basicsr files. Thank you.
