### ISSUE TITLE
GPU not working

### ISSUE THREAD

**Issue by Azemar** [xinntao/Real-ESRGAN#202]
Hello.
I use original Real-ESRGAN and it uses only the CPU. Although the portable version uses a GPU, it does not suit me. How do I use the GPU on the original version?

My pip-list:
Python 3.7.2
CUDA 11.0

```
1. absl-py                 1.0.0
2. addict                  2.4.0
3. basicsr                 1.3.4.9
4. cachetools              4.2.4
5. certifi                 2021.10.8
6. charset-normalizer      2.0.9
7. colorama                0.4.4
8. cycler                  0.11.0
9. dataclasses             0.6
10. facexlib                0.2.1.1
11. filterpy                1.4.5
12. fonttools               4.28.5
13. future                  0.18.2
14. gfpgan                  0.2.4
15. google-auth             2.3.3
16. google-auth-oauthlib    0.4.6
17. grpcio                  1.43.0
18. idna                    3.3
19. imageio                 2.13.5
20. importlib-metadata      4.10.0
21. kiwisolver              1.3.2
22. llvmlite                0.37.0
23. lmdb                    1.2.1
24. Markdown                3.3.6
25. matplotlib              3.5.1
26. networkx                2.6.3
27. numba                   0.54.1
28. numpy                   1.20.3
29. oauthlib                3.1.1
30. opencv-python           4.5.4.60
31. packaging               21.3
32. Pillow                  8.4.0
33. pip                     21.3.1
34. protobuf                3.19.1
35. pyasn1                  0.4.8
36. pyasn1-modules          0.2.8
37. pyparsing               3.0.6
38. python-dateutil         2.8.2
39. PyWavelets              1.2.0
40. PyYAML                  6.0
41. realesrgan              0.2.3.0        z:\2
42. requests                2.26.0
43. requests-oauthlib       1.3.0
44. rsa                     4.8
45. scikit-image            0.19.1
46. scipy                   1.7.3
47. setuptools              60.1.0
48. six                     1.16.0
49. tb-nightly              2.8.0a20211224
50. tensorboard-data-server 0.6.1
51. tensorboard-plugin-wit  1.8.0
52. tifffile                2021.11.2
53. torch                   1.10.1
54. torchvision             0.11.2
55. tqdm                    4.62.3
56. typing_extensions       4.0.1
57. urllib3                 1.26.7
58. Werkzeug                2.0.2
59. wheel                   0.37.1
60. yapf                    0.31.0
61. zipp                    3.6.0
```

**Comment by kodxana** [comment]
Have you tried install PyTorch from this?
https://pytorch.org/get-started/locally/

**Comment by Azemar** [comment]
> Have you tried install PyTorch from this?

I installed the following packages:
`pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

But I get the following error:

> Error CUDA out of memory. Tried to allocate 294.00 MiB (GPU 0; 6.00 GiB total capacity; 1.79 GiB already allocated; 2.27 GiB free; 1.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> If you encounter CUDA out of memory, try to set --tile with a smaller number.
> Testing 1 1
> Traceback (most recent call last):
>   File "inference_realesrgan.py", line 128, in <module>
>     main()
>   File "inference_realesrgan.py", line 103, in main
>     if len(img.shape) == 3 and img.shape[2] == 4:
> AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by kodxana** [comment]
You are running out of memory you might want to use
--tile 265 in your command :)

**Comment by Azemar** [comment]
> You are running out of memory you might want to use
> --tile 265 in your command :)

--tile disfigures the image with a grid

**Comment by kodxana** [comment]
--tile works fine the grid issue is with -s (aka scale settings) so you cant use x4 model and set scale to 2.

**Comment by JacobMGEvans** [comment]
I thought everything was portable (I am running into similar issue) I am in a WSL environment running conda with the same
`pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

I am however getting 
```sh
./esgran/realesrgan-ncnn-vulkan -i oh-jeez.png -o oh-jeez-upscale.png -s
2 -v
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  fp16-p/s/a=1/0/0  int8-p/s/a=1/0/0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  subgroup=4  basic=0  vote=0  ballot=0  shuffle=0
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
```

**Comment by kodxana** [comment]
WSL is not with GPU support tested it and it won't work cause WSL do not support Vulcan API's

**Comment by JacobMGEvans** [comment]
sidenote that might interest you kodxana, I was able to get https://github.com/nerdyrodent/VQGAN-CLIP to work in WSL and nerdyreodent's diffusion CLIP repo led me here.

**Comment by JacobMGEvans** [comment]
> WSL is not with GPU support tested it and it won't work cause WSL do not support Vulcan API's

I'm gonna try a few more things then likely fail, give up and download the Windows binaries. If for some horrific reason those don't work I will open a new issue with log dumps 😄

**Comment by kodxana** [comment]
> sidenote that might interest you kodxana, I was able to get https://github.com/nerdyrodent/VQGAN-CLIP to work in WSL and nerdyreodent's diffusion CLIP repo led me here. 

It's cause it's use VSGAN that it's using pytorch version of resergan. Only the Vulcan implementation has issues with colab and WSL.
