### ISSUE TITLE
error of processing all videos in upload folder

### ISSUE THREAD

**Issue by GeorvityLabs** [xinntao/Real-ESRGAN#232]
when running
`!python inference_realesrgan_video.py --input upload -n RealESRGANv2-animevideo-xsx2 -s 4 -v -a --half --suffix outx2
`
I'm getting :

```
Traceback (most recent call last):
  File "inference_realesrgan_video.py", line 199, in <module>
    main()
  File "inference_realesrgan_video.py", line 108, in main
    if mimetypes.guess_type(args.input)[0].startswith('video'):  # is a video file
AttributeError: 'NoneType' object has no attribute 'startswith'


```
I'm unable to run the inference on the videos inside the upload folder one after the other.

Hope someone can help fix this issue.

**Comment by GeorvityLabs** [comment]
I want to run inference on all files in a folder , not one file at a time manually.

**Comment by GeorvityLabs** [comment]
@xinntao hope you can have a look at this.
I'm using the anime video colab notebook.

**Comment by kodxana** [comment]
@GeorvityLabs Script is made to input one video file. Video gets extracted into frames then upscaled and finally rendered back to video. Also if you run it on colab you might run out of storage space when upscaling multiple videos.
