### ISSUE TITLE
How do put a path with space in step 5?

### ISSUE THREAD

**Issue by copapp** [xinntao/Real-ESRGAN#240]
let say that I have a folder name /content/My Video/this video.mp4 when I put "", it doesn't recognized the path 
/content/My: No such file or directory

**Comment by msjie1** [comment]
Hi, how do you handle this,
Traceback (most recent call last):
  File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 201, in <module>
    main()
  File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 110, in main
    if mimetypes.guess_type(args.input)[0].startswith('demo'):  # is a video file 
AttributeError: 'NoneType' object has no attribute 'startswith'
Can you tell me the detailed steps and an example. Thanks

**Comment by msjie1** [comment]
Hello, how to deal with this problem, I use pycharm to run this project instead of CMD. If you can, please teach me how to do it in detail and give some examples. Thank you
Traceback (most recent call last):
  File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 201, in <module>
    main()
  File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 110, in main
    if mimetypes.guess_type(args.input)[0].startswith('video'):  # is a video file   是一个视频文件
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by jackthenewbie** [comment]
> Hello, how to deal with this problem, I use pycharm to run this project instead of CMD. If you can, please teach me how to do it in detail and give some examples. Thank you
> 
> Traceback (most recent call last):
> 
>   File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 201, in <module>
> 
>     main()
> 
>   File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 110, in main
> 
>     if mimetypes.guess_type(args.input)[0].startswith('video'):  # is a video file   是一个视频文件
> 
> AttributeError: 'NoneType' object has no attribute 'startswith'

I think you should open a new issue about this one, but I guess your input is not a path to mp4(or media type file)
And you have to run this project with cmd, just open google colab example from readme and start from there mate.
