### ISSUE TITLE
Error regarding circular_lowpass_kernel

### ISSUE THREAD

**Issue by manjus3** [xinntao/Real-ESRGAN#27]
Hi, I just updated my git repo to the latest codebase. When I run the inference code, I get the following errors:
python inference_realesrgan.py --scale 4 --model_path experiments/pretrained_models/RealESRGAN_x4plus.pth --input inputs
"
Traceback (most recent call last):
  File "C:\msys64\home\manju\tools\esrgan\Real-ESRGAN\inference_realesrgan.py", line 6, in <module>
    from realesrgan import RealESRGANer
  File "C:\msys64\home\manju\tools\esrgan\Real-ESRGAN\realesrgan\__init__.py", line 3, in <module>
    from .data import *
  File "C:\msys64\home\manju\tools\esrgan\Real-ESRGAN\realesrgan\data\__init__.py", line 10, in <module>
    _dataset_modules = [importlib.import_module(f'realesrgan.data.{file_name}') for file_name in dataset_filenames]
  File "C:\msys64\home\manju\tools\esrgan\Real-ESRGAN\realesrgan\data\__init__.py", line 10, in <listcomp>
    _dataset_modules = [importlib.import_module(f'realesrgan.data.{file_name}') for file_name in dataset_filenames]
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\msys64\home\manju\tools\esrgan\Real-ESRGAN\realesrgan\data\realesrgan_dataset.py", line 9, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
ImportError: cannot import name 'circular_lowpass_kernel' from 'basicsr.data.degradations' (C:\Python39\lib\site-packages\basicsr\data\degradations.py)
"

Thanks,
Manju

**Comment by panshaohua** [comment]
[https://github.com/xinntao/Real-ESRGAN/issues/15#issuecomment-893244332](url)

**Comment by panshaohua** [comment]
pip install basicsr==1.3.3.10

**Comment by manjus3** [comment]
Thanks, @panshaohua. That worked!
