### ISSUE TITLE
 can't open/read file: check file path/integrity

### ISSUE THREAD

**Issue by Mcford-git** [xinntao/Real-ESRGAN#279]
Images works but video cann't
It shows：

Testing 0 video
[ WARN:0@2.976] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('inputs\video'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\mcfor\Real-ESRGAN\inference_realesrgan.py", line 128, in <module>
    main()
  File "C:\Users\mcfor\Real-ESRGAN\inference_realesrgan.py", line 103, in main
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'

But I have ‘video’ folder in i、‘inputs’，why it happened？

**Comment by khairulsynapse** [comment]
Please try to put in only the video file in the 'inputs ' folder. Remove the video folder and try to re-run again.
