### ISSUE TITLE
pdf converted image will report error

### ISSUE THREAD

**Issue by chaozuoyedemengxin** [xinntao/Real-ESRGAN#307]
[ WARN:0@2.890] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('inputs\2023鏉庢案涔愭暟瀛﹀熀纭€杩囧叧660棰?Traceback (most recent call last):
  File "E:\Anaconda3\Real-ESRGAN-master\inference_realesrgan.py", line 136, in <module>
    main()
  File "E:\Anaconda3\Real-ESRGAN-master\inference_realesrgan.py", line 111, in main
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by chaozuoyedemengxin** [comment]
问题解决，文件名不能含有中文
