### ISSUE TITLE
setup error on ubuntu 22.04

### ISSUE THREAD

**Issue by TailsxKyuubi** [xinntao/Real-ESRGAN#327]
While the install process the compilation of numpy 1.20.3 fails on ubuntu 22.04. newer versions are working. would it be possible to bump the version to 1.21.x or 1.22.x? according to the error messages the problem might be the missing python 3.10 support.

**Comment by 6630507** [comment]
This worked for me:

`pip install gfpgan numpy=1.21.2`

**Comment by krummrey** [comment]
I've tried that and pip seems to install it fine, but then I get this error:
```
Traceback (most recent call last):
  File "/Users/jan/Documents/ML/Real-ESRGAN/inference_realesrgan.py", line 128, in <module>
    main()
  File "/Users/jan/Documents/ML/Real-ESRGAN/inference_realesrgan.py", line 81, in main
    from gfpgan import GFPGANer
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/gfpgan/__init__.py", line 4, in <module>
    from .models import *
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/gfpgan/models/__init__.py", line 10, in <module>
    _model_modules = [importlib.import_module(f'gfpgan.models.{file_name}') for file_name in model_filenames]
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/gfpgan/models/__init__.py", line 10, in <listcomp>
    _model_modules = [importlib.import_module(f'gfpgan.models.{file_name}') for file_name in model_filenames]
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/gfpgan/models/gfpgan_model.py", line 6, in <module>
    from basicsr.losses.losses import r1_penalty
ModuleNotFoundError: No module named 'basicsr.losses.losses'
```
basicsr is installed and even force reinstalled
