### ISSUE TITLE
how do i use my trained model?

### ISSUE THREAD

**Issue by nicolai256** [xinntao/Real-ESRGAN#342]
when trying to use my trained model it wants to use a `.param` file, the `.bin` and `.param` file are not being generated?
how do i use my `.pth` file?
thanks

**Comment by darkcristle** [comment]
First off I'm not the author, but based off of what I can see.

Typically the model class is needs to be defined in the program first before the .pth can be used.  The .pth only contains the weights not the actual structure of the model.  If you look in the realesrgan/arch folder you can see the model classes.  If you are trying to run the model in an external program you will need to define the class yourself or copy the code and its dependencies into your program.

**Comment by nicolai256** [comment]
> First off I'm not the author, but based off of what I can see.
> 
> Typically the model class is needs to be defined in the program first before the .pth can be used. The .pth only contains the weights not the actual structure of the model. If you look in the realesrgan/arch folder you can see the model classes. If you are trying to run the model in an external program you will need to define the class yourself or copy the code and its dependencies into your program.

i don't understand..
i'm trying to run my custom model with inference_realesrgan.py and realesrgan-ncnn-vulkan.exe
```
 C:\deepdream-test\Real-ESRGAN-master>inference_realesrgan.py -n "tripx4latest.pth" -i 1.png -o 8.png --face_enhance
C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 124, in <module>
    main()
  File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 64, in main
    raise ValueError(f'Model {args.model_name} does not exist.')
ValueError: Model tripx4latest does not exist.
```
it says the file doesn'texist but it does..
if i run the full path to the model it says this..
```
C:\deepdream-test\Real-ESRGAN-master>inference_realesrgan.py -n "C:\deepdream-test\Real-ESRGAN-master\tripx4latest.pth" -i 1.png -o 8.png --face_enhance
C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 124, in <module>
    main()
  File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 68, in main
    scale=netscale,
UnboundLocalError: local variable 'netscale' referenced before assignment
```
realesrgan-ncnn-vulkan.exe leads to this..
```
C:\deepdream-test\Real-ESRGAN-master>realesrgan-ncnn-vulkan.exe -i 1.png -o 8.png -n tripx4latest
[0 NVIDIA GeForce RTX 3090]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3090]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3090]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3090]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
_wfopen C:\deepdream-test\Real-ESRGAN-master\models/tripx4latest.param failed

```

**Comment by Minoo-Hsn** [comment]
> > First off I'm not the author, but based off of what I can see.
> > Typically the model class is needs to be defined in the program first before the .pth can be used. The .pth only contains the weights not the actual structure of the model. If you look in the realesrgan/arch folder you can see the model classes. If you are trying to run the model in an external program you will need to define the class yourself or copy the code and its dependencies into your program.
> 
> i don't understand.. i'm trying to run my custom model with inference_realesrgan.py and realesrgan-ncnn-vulkan.exe
> 
> ```
>  C:\deepdream-test\Real-ESRGAN-master>inference_realesrgan.py -n "tripx4latest.pth" -i 1.png -o 8.png --face_enhance
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
>   warnings.warn("loaded more than 1 DLL from .libs:"
> <frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
> Traceback (most recent call last):
>   File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 124, in <module>
>     main()
>   File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 64, in main
>     raise ValueError(f'Model {args.model_name} does not exist.')
> ValueError: Model tripx4latest does not exist.
> ```
> 
> it says the file doesn'texist but it does.. if i run the full path to the model it says this..
> 
> ```
> C:\deepdream-test\Real-ESRGAN-master>inference_realesrgan.py -n "C:\deepdream-test\Real-ESRGAN-master\tripx4latest.pth" -i 1.png -o 8.png --face_enhance
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
>   warnings.warn("loaded more than 1 DLL from .libs:"
> <frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
> Traceback (most recent call last):
>   File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 124, in <module>
>     main()
>   File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 68, in main
>     scale=netscale,
> UnboundLocalError: local variable 'netscale' referenced before assignment
> ```
> 
> realesrgan-ncnn-vulkan.exe leads to this..
> 
> ```
> C:\deepdream-test\Real-ESRGAN-master>realesrgan-ncnn-vulkan.exe -i 1.png -o 8.png -n tripx4latest
> [0 NVIDIA GeForce RTX 3090]  queueC=2[8]  queueG=0[16]  queueT=1[2]
> [0 NVIDIA GeForce RTX 3090]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
> [0 NVIDIA GeForce RTX 3090]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
> [0 NVIDIA GeForce RTX 3090]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
> _wfopen C:\deepdream-test\Real-ESRGAN-master\models/tripx4latest.param failed
> ```

I have same issue. Were you able to solve it? Thanks.

**Comment by cjw19951005** [comment]
> > 首先，我不是作者，而是基于我所看到的。
> > 通常，在使用 .pth 之前，需要先在程序中定义模型类。.pth 仅包含权重，不包含模型的实际结构。如果你在 realesrgan/arch 文件夹中查看，你可以看到模型类。如果尝试在外部程序中运行模型，则需要自己定义类或将代码及其依赖项复制到程序中。
> 
> 我不明白。。我正在尝试使用inference_realesrgan.py和realesrgan-ncnn-vulkan运行我的自定义模型.exe
> 
> ```
>  C:\deepdream-test\Real-ESRGAN-master>inference_realesrgan.py -n "tripx4latest.pth" -i 1.png -o 8.png --face_enhance
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
>   warnings.warn("loaded more than 1 DLL from .libs:"
> <frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
> Traceback (most recent call last):
>   File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 124, in <module>
>     main()
>   File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 64, in main
>     raise ValueError(f'Model {args.model_name} does not exist.')
> ValueError: Model tripx4latest does not exist.
> ```
> 
> 它说文件没有特西斯特，但它有。如果我运行模型的完整路径，它说这个.
> 
> ```
> C:\deepdream-test\Real-ESRGAN-master>inference_realesrgan.py -n "C:\deepdream-test\Real-ESRGAN-master\tripx4latest.pth" -i 1.png -o 8.png --face_enhance
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
> C:\Users\Gebruiker\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_base\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
>   warnings.warn("loaded more than 1 DLL from .libs:"
> <frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
> Traceback (most recent call last):
>   File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 124, in <module>
>     main()
>   File "C:\deepdream-test\Real-ESRGAN-master\inference_realesrgan.py", line 68, in main
>     scale=netscale,
> UnboundLocalError: local variable 'netscale' referenced before assignment
> ```
> 
> realesrgan-ncnn-vulkan.exe导致这种情况。
> 
> ```
> C:\deepdream-test\Real-ESRGAN-master>realesrgan-ncnn-vulkan.exe -i 1.png -o 8.png -n tripx4latest
> [0 NVIDIA GeForce RTX 3090]  queueC=2[8]  queueG=0[16]  queueT=1[2]
> [0 NVIDIA GeForce RTX 3090]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
> [0 NVIDIA GeForce RTX 3090]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
> [0 NVIDIA GeForce RTX 3090]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
> _wfopen C:\deepdream-test\Real-ESRGAN-master\models/tripx4latest.param failed
> ```

请问这个问题解决了吗？我也遇到了

**Comment by cliffordkleinsr** [comment]
#189
