### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' when validating

### ISSUE THREAD

**Issue by marcb19990** [xinntao/Real-ESRGAN#389]
Following (https://github.com/xinntao/Real-ESRGAN/blob/master/docs/Training.md) for basic training. It works when I only train, however when using validation parameters it gives me this error.

**Traceback (most recent call last):
  File "realesrgan/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/home/user/project/ESRGAN/lib/python3.7/site-packages/basicsr/train.py", line 193, in train_pipeline
    model.validation(val_loader, current_iter, tb_logger, opt['val']['save_img'])
  File "/home/user/project/ESRGAN/lib/python3.7/site-packages/basicsr/models/base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "/project/user/ESRGAN/Real-ESRGAN/realesrgan/models/realesrnet_model.py", line 187, in nondist_validation
    super(RealESRNetModel, self).nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "/home/user/project/ESRGAN/lib/python3.7/site-packages/basicsr/models/sr_model.py", line 145, in nondist_validation
    self._initialize_best_metric_results(dataset_name)
  File "/home/user/project/ESRGAN/lib/python3.7/site-packages/basicsr/models/base_model.py", line 60, in _initialize_best_metric_results
    better = content.get('better', 'higher')
AttributeError: 'NoneType' object has no attribute 'get'**

Current setup:
  # Uncomment these for validation
  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: 256to1024/valid/_256_1024/hr_1024/images
    dataroot_lq: 256to1024/valid/_256_1024/lr_256/images
    io_backend:
      type: disk

I can see that the images are seen with the output:

2022-07-13 13:02:42,084 INFO: Dataset [RealESRGANDataset] - 256to1024 is built.
2022-07-13 13:02:42,084 INFO: Training statistics:
        Number of train images: 8983
        Dataset enlarge ratio: 1
        Batch size per gpu: 1
        World size (gpu number): 1
        Require iter number per epoch: 8983
        Total epochs: 112; iters: 1000000.
2022-07-13 13:02:42,109 INFO: Dataset [PairedImageDataset] - validation is built.
2022-07-13 13:02:42,110 INFO: **Number of val images/folders in validation: 494**
2022-07-13 13:02:42,712 INFO: Network [RRDBNet] is created.

**Comment by jojupiter** [comment]
I have the same problem. How can I solve it?
