### ISSUE TITLE
Scale mismatches in Training, finetune_realesrgan_x4plus_pairdata.yaml

### ISSUE THREAD

**Issue by muhammadAgfian96** [xinntao/Real-ESRGAN#409]
Hi, Thanks for the great projects!

i have a problem with training finetune paired data using **finetune_realesrgan_x4plus_pairdata.yml**.
i do manually resize my HQ data using this code to produce LQ data

```
import cv2
import os
from tqdm import tqdm


path = 'dataset/batch-1/hq'
path_dst = 'dataset/batch-1/lq'

scale_x = 0.248 # downscale 4x from hq image 
scale_y = 0.248
os.makedirs(path_dst, exist_ok=True)

for fname in tqdm(os.listdir(path)):
    dst_fname = os.path.join(path_dst, fname)
    ori_path = os.path.join(path, fname)
    img = cv2.imread(ori_path)
    img_resized = cv2.resize(img, fx=scale_x, fy=scale_y, dsize=None,  interpolation=cv2.INTER_CUBIC)
    cv2.imwrite(dst_fname, img_resized)
```
from this, i have HQ and LQ data image

but it keep give me this error
```   
Traceback (most recent call last):
  File "realesrgan/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/opt/conda/lib/python3.8/site-packages/basicsr/train.py", line 157, in train_pipeline
    train_data = prefetcher.next()
  File "/opt/conda/lib/python3.8/site-packages/basicsr/data/prefetch_dataloader.py", line 76, in next
    return next(self.loader)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1251, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 463, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/real-sr/realesrgan/data/realesrgan_paired_dataset.py", line 94, in __getitem__
    img_gt, img_lq = paired_random_crop(img_gt, img_lq, gt_size, scale, gt_path)
  File "/opt/conda/lib/python3.8/site-packages/basicsr/data/transforms.py", line 64, in paired_random_crop
    raise ValueError(f'Scale mismatches. GT ({h_gt}, {w_gt}) is not {scale}x ',
ValueError: ('Scale mismatches. GT (850, 1275) is not 4x ', 'multiplication of LQ (211, 316).')
```

Please let me know, where i do mistakes/miss guide for training paired data.

Thanks in Advance.

**Comment by muhammadAgfian96** [comment]
```
# general settings
name: finetune_RealESRGANx4plus_400k_pairdata
model_type: RealESRGANModel
scale: 4
num_gpu: auto
manual_seed: 0

# USM the ground-truth
l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False

high_order_degradation: False # do not use the high-order degradation generation process

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: RealESRGANPairedDataset
    dataroot_gt: dataset/batch-1
    dataroot_lq: dataset/batch-1
    meta_info: datasets/batch-1/meta_info/meta_info_b1_sub_pair.txt
    io_backend:
      type: disk

    gt_size: 200
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 5
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  # val:
  #   name: validation
  #   type: PairedImageDataset
  #   dataroot_gt: path_to_gt
  #   dataroot_lq: path_to_lq
  #   io_backend:
  #     type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

# path
path:
  # use the pre-trained Real-ESRNet model
  pretrain_network_g: experiments/pretrained_models/RealESRGAN_x4plus.pth
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: experiments/pretrained_models/RealESRGAN_x4plus_netD.pth
  param_key_d: params
  strict_load_d: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  # perceptual loss (content and style losses)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  # gan loss
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

# Uncomment these for validation
# validation settings
# val:
#   val_freq: !!float 5e3
#   save_img: True

#   metrics:
#     psnr: # metric name
#       type: calculate_psnr
#       crop_border: 4
#       test_y_channel: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
```

**Comment by muhammadAgfian96** [comment]
it solved.

**Comment by koihoo** [comment]
> it solved.

please tell me how to solve this problem？

**Comment by aldogan17** [comment]
I have the same problem.

**Comment by DongKat** [comment]
@koihoo , @aldogan17 the LR version was created with rounded size. So to solve this, crop your HR to a size that divisible by 4, then resize into LR.
