### ISSUE TITLE
请问运行之后出现这种报错是什么原因，怎么解决呢

### ISSUE THREAD

**Issue by nan2002321** [xinntao/Real-ESRGAN#465]
Using executable: D:\APP\Realesrgan_GUI\realesrgan-ncnn-vulkan.exe
vkCreateInstance failed -9
vkCreateInstance failed -9
invalid gpu device
Traceback (most recent call last):
File "task.py", line 243, in taskRunner
File "task.py", line 95, in run
subprocess.CalledProcessError: Command '('D:\APP\Realesrgan_GUI\realesrgan-ncnn-vulkan.exe', '-v', '-i', 'C:\Users\86177\Pictures\Saved Pictures\1.png', '-o', 'C:\Users\86177\AppData\Local\Temp\JBhfeTEjokb1UD6h.png', '-s', '4', '-t', '256', '-n', 'realesrgan-x4plus-anime', '-g', '0', '')' returned non-zero exit status 4294967295.

**Comment by suifengqjn** [comment]
python 要是一门编译型语言就好了，直接解决90%以上的问题

**Comment by SamHou0** [comment]
我也遇到了这个问题，可以尝试升级电脑的显卡驱动解决
