### ISSUE TITLE
[Training Issue] ModuleNotFoundError: No module named 'realesrgan'

### ISSUE THREAD

**Issue by akineeic** [xinntao/Real-ESRGAN#49]
Hi,
When I follow the training guide to train the model, an error occurred as follows:
```
Traceback (most recent call last):
  File "realesrgan/train.py", line 5, in <module>
    import realesrgan.archs
ModuleNotFoundError: No module named 'realesrgan'

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/SDD/zzm/env/torch1.7/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/SDD/zzm/env/torch1.7/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/SDD/zzm/env/torch1.7/bin/python', '-u', 'realesrgan/train.py', '--local_rank=3', '-opt', 'options/train_realesrnet_x2plus.yml', '--launcher', 'pytorch', '--debug']' returned non-zero exit status 1.
```

Execute command：
```
python -m torch.distributed.launch --nproc_per_node=4 --master_port=4321 realesrgan/train.py -opt options/train_realesrnet_x2plus.yml --launcher pytorch --debug
```

What should I do to avoid this error?

**Comment by akineeic** [comment]
I found I forgot to run the `setup.py`. This issue is fixed by running the script, thanks for your attention.

**Comment by JOHG-sudo** [comment]
How to do this
