### ISSUE TITLE
UnboundLocalError: local variable 'output_tile' referenced before assignment

### ISSUE THREAD

**Issue by SteveMama** [xinntao/Real-ESRGAN#516]
Testing 0 frame0
Error "slow_conv2d_cpu" not implemented for 'Half'
	Tile 1/240
Traceback (most recent call last):
  File "inference_realesrgan.py", line 166, in <module>
    main()
  File "inference_realesrgan.py", line 145, in main
    _, _, output = face_enhancer.enhance(img, has_aligned=False, only_center_face=False, paste_back=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gfpgan/utils.py", line 139, in enhance
    bg_img = self.bg_upsampler.enhance(img, outscale=self.upscale)[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/Real-ESRGAN/realesrgan/utils.py", line 221, in enhance
    self.tile_process()
  File "/content/Real-ESRGAN/realesrgan/utils.py", line 179, in tile_process
    output_start_x:output_end_x] = output_tile[:, :, output_start_y_tile:output_end_y_tile,
UnboundLocalError: local variable 'output_tile' referenced before assignment

**The inference doesn't happen as expected. keeps putting out this result.**

**Comment by Microslargh** [comment]
I also met this problem how to solve it?
