### ISSUE TITLE
while parsing a block mapping did not find expected key

### ISSUE THREAD

**Issue by wolfam0108** [xinntao/Real-ESRGAN#58]
Hello, when starting in Windows 10, with the command:
`"python realesrgan/train.py -opt options/train_realesrnet_x4plus.yml"`

I get at the output:

PS C:\Users\vova\Desktop\Real-ESRGAN-master> python realesrgan/train.py -opt options/train_realesrnet_x4plus.yml
Traceback (most recent call last):
  File "realesrgan/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "C:\Users\vova\AppData\Roaming\Python\Python38\site-packages\basicsr\train.py", line 93, in train_pipeline
    opt = parse_options(root_path, is_train=True)
  File "C:\Users\vova\AppData\Roaming\Python\Python38\site-packages\basicsr\utils\options.py", line 127, in parse_options
    opt = parse(args.opt, root_path, is_train=is_train, debug=args.debug)
  File "C:\Users\vova\AppData\Roaming\Python\Python38\site-packages\basicsr\utils\options.py", line 49, in parse
    opt = yaml.load(f, Loader=Loader)
  File "C:\Users\vova\AppData\Roaming\Python\Python38\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\vova\AppData\Roaming\Python\Python38\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml\_yaml.pyx", line 707, in yaml._yaml.CParser.get_single_node
  File "yaml\_yaml.pyx", line 725, in yaml._yaml.CParser._compose_document
  File "yaml\_yaml.pyx", line 776, in yaml._yaml.CParser._compose_node
  File "yaml\_yaml.pyx", line 890, in yaml._yaml.CParser._compose_mapping_node
  File "yaml\_yaml.pyx", line 776, in yaml._yaml.CParser._compose_node
  File "yaml\_yaml.pyx", line 892, in yaml._yaml.CParser._compose_mapping_node
  File "yaml\_yaml.pyx", line 905, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a block mapping
  in "options/train_realesrnet_x4plus.yml", line 35, column 3
did not find expected key
  in "options/train_realesrnet_x4plus.yml", line 73, column 4

In the settings of train_realesrnet_x4plus.yml the following:
....
# dataset and data loader settings
datasets:
  train:
    name: Manga_set2
    type: RealESRGANDataset
    dataroot_gt: datasets/Manga_set2
    meta_info: datasets/Manga_set2/meta_info/Manga_set2.txt
    io_backend:
      type: disk
...

...
   #Uncomment these for validation
   val:
     name: validation
     type: PairedImageDataset
     dataroot_gt: datasets/Manga_set2/GT_V
     dataroot_lq: datasets/Manga_set2/LQ_V
     io_backend:
       type: disk
....

**Comment by xinntao** [comment]
@wolfam0108 

It seems that your yaml file has wrong spaces/indentation. Please check it.

**Comment by wolfam0108** [comment]
Thanks for the answer.
I removed the "#" without replacing it with a space.
