### ISSUE TITLE
Error when adding -t for tiling

### ISSUE THREAD

**Issue by AntonHarboe** [xinntao/Real-ESRGAN#633]
I get this problem after i run out of CUDA memory, and then try to add the tile (-t) command.

Traceback (most recent call last):
  File "C:\Users\anton\Real-ESRGAN\inference_realesrgan.py", line 166, in <module>
    main()
  File "C:\Users\anton\Real-ESRGAN\inference_realesrgan.py", line 145, in main
    _, _, output = face_enhancer.enhance(img, has_aligned=False, only_center_face=False, paste_back=True)
  File "C:\Users\anton\anaconda\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\anton\anaconda\lib\site-packages\gfpgan\utils.py", line 139, in enhance
    bg_img = self.bg_upsampler.enhance(img, outscale=self.upscale)[0]
  File "C:\Users\anton\anaconda\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\anton\Real-ESRGAN\realesrgan\utils.py", line 221, in enhance
    self.tile_process()
  File "C:\Users\anton\Real-ESRGAN\realesrgan\utils.py", line 179, in tile_process
    output_start_x:output_end_x] = output_tile[:, :, output_start_y_tile:output_end_y_tile,
UnboundLocalError: local variable 'output_tile' referenced before assignment

I dont know how to make it work...

**Comment by asuka-su** [comment]
This is usually caused by CUDA out of memory. The code is set to keep running even if output_tile does not generate properly. 
See file utils.py line 158.
