### ISSUE TITLE
Module not found error google colab

### ISSUE THREAD

**Issue by ashis-paul-blox** [xinntao/Real-ESRGAN#647]
While running the inference model, getting this error
```bash
/content/Real-ESRGAN
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/content/Real-ESRGAN/inference_realesrgan.py", line 8, in <module>
    from realesrgan import RealESRGANer
  File "/content/Real-ESRGAN/realesrgan/__init__.py", line 6, in <module>
    from .version import *
ModuleNotFoundError: No module named 'realesrgan.version'
```

**Comment by huangxinping** [comment]
`python setup.py develop` will solve the problem.
