### ISSUE TITLE
Stumped! FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by cbroker1** [xinntao/Real-ESRGAN#694]
Fresh Windows Env, Fresh `conda` env. In the past I've installed Real-Esrgan on multiple machines (win/linux) and used the same approach to install (via Readme) without issue.

What I'm experiencing: 
GPU utilization occurs in `inference_realesrgan.py` for single image processing without issue (verified via Task Manager, see image below) and crashed out with `inference_realesrgan_video.py`.

Error output:
```
ffmpeg -f concat -safe 0 -i z_out/video_vidlist.txt -c copy z_out\video_out.mp4
c:\Users\carlb\anaconda3\envs\upscale\Lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(

inference:   0%|          | 0/2 [00:00<?, ?sub_video/s]c:\Users\carlb\anaconda3\envs\upscale\Lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
c:\Users\carlb\anaconda3\envs\upscale\Lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "c:\Users\carlb\anaconda3\envs\upscale\Scripts\Real-ESRGAN\inference_realesrgan_video.py", line 398, in <module>
    main()
  File "c:\Users\carlb\anaconda3\envs\upscale\Scripts\Real-ESRGAN\inference_realesrgan_video.py", line 390, in main
    run(args)
  File "c:\Users\carlb\anaconda3\envs\upscale\Scripts\Real-ESRGAN\inference_realesrgan_video.py", line 319, in run
    subprocess.call(cmd)
  File "c:\Users\carlb\anaconda3\envs\upscale\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\carlb\anaconda3\envs\upscale\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\carlb\anaconda3\envs\upscale\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

inference:   0%|          | 0/2 [00:03<?, ?sub_video/s]
```

My `pip freeze` and `nvidia-smi` outputs are below as well. 

![image](https://github.com/xinntao/Real-ESRGAN/assets/43118284/78294ed3-a7a1-412e-b92c-2d3cd57860dc)

My pip freeze (please excuse the lack of formatting): 
`(upscale)
carlb@DESKTOP-5O8688P MINGW64 /
$ pip freeze
absl-py==2.0.0
addict==2.4.0
asttokens==2.4.0
backcall==0.2.0
basicsr==1.4.2
cachetools==5.3.1
certifi==2022.12.7
charset-normalizer==2.1.1
colorama==0.4.6
comm==0.1.4
contourpy==1.1.1
cycler==0.12.0
debugpy==1.8.0
decorator==5.1.1
executing==2.0.0
facexlib==0.3.0
ffmpeg==1.4
filelock==3.9.0
filterpy==1.4.5
fonttools==4.43.0
future==0.18.3
gfpgan==1.3.8
google-auth==2.23.2
google-auth-oauthlib==1.0.0
grpcio==1.59.0
idna==3.4
imageio==2.31.4
importlib-metadata==6.8.0
ipykernel==6.25.2
ipython==8.16.0
jedi==0.19.0
Jinja2==3.1.2
jupyter_client==8.3.1
jupyter_core==5.3.2
kiwisolver==1.4.5
lazy_loader==0.3
llvmlite==0.41.0
lmdb==1.4.1
Markdown==3.4.4
MarkupSafe==2.1.2
matplotlib==3.8.0
matplotlib-inline==0.1.6
mpmath==1.3.0
nest-asyncio==1.5.8
networkx==3.0
numba==0.58.0
numpy==1.24.1
oauthlib==3.2.2
opencv-python==4.8.1.78
packaging==23.1
parso==0.8.3
pickleshare==0.7.5
Pillow==9.3.0
platformdirs==3.10.0
prompt-toolkit==3.0.39
protobuf==4.23.4
psutil==5.9.5
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
Pygments==2.16.1
pyparsing==3.1.1
python-dateutil==2.8.2
PyWavelets==1.4.1
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.1
-e git+https://github.com/xinntao/Real-ESRGAN.git@5ca1078535923d485892caee7d7804380bfc87fd#egg=realesrgan
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-image==0.21.0
scipy==1.11.3
six==1.16.0
stack-data==0.6.3
sympy==1.12
tb-nightly==2.15.0a20230930
tensorboard-data-server==0.7.1
tifffile==2023.9.26
tomli==2.0.1
torch==2.0.1+cu118
torchaudio==2.0.2+cu118
torchvision==0.15.2+cu118
tornado==6.3.3
tqdm==4.66.1
traitlets==5.10.1
typing_extensions==4.4.0
urllib3==1.26.13
wcwidth==0.2.8
Werkzeug==3.0.0
yapf==0.40.2
zipp==3.17.0`

**Comment by cbroker1** [comment]
no response, just closing.
