### ISSUE TITLE
What i can do?

### ISSUE THREAD

**Issue by Keiser04** [xinntao/Real-ESRGAN#715]
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Testing 0 CODE_OF_CONDUCT
Traceback (most recent call last):
  File "/content/Real-ESRGAN/inference_realesrgan.py", line 166, in <module>
    main()
  File "/content/Real-ESRGAN/inference_realesrgan.py", line 138, in main
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by SuperVirtuel** [comment]
same here, it finds the file but i get the error :

(RESRGAN) C:\Users\X\DEV\Real-ESRGAN>python inference_realesrgan.py -n RealESRGAN_x4plus_anime_6B -i inputs
Testing 0 test_video_1
Traceback (most recent call last):
  File "inference_realesrgan.py", line 166, in <module>
    main()
  File "inference_realesrgan.py", line 138, in main
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by AIhasArrived** [comment]
Any solution @SuperVirtuel  and @Keiser04 ??

**Comment by Keiser04** [comment]
I don't remember, I kind of made a simple collab but it only has the upscae of anime style and that's where it goes.

> Any solution @SuperVirtuel and @Keiser04 ??

**Comment by AIhasArrived** [comment]
Ouki, could you update me on the things you are using nowadays, or youhave used and found useful since that time?
Thanks

**Comment by dummyuser-123** [comment]
> /usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional. warnings.warn( Testing 0 CODE_OF_CONDUCT Traceback (most recent call last): File "/content/Real-ESRGAN/inference_realesrgan.py", line 166, in main() File "/content/Real-ESRGAN/inference_realesrgan.py", line 138, in main if len(img.shape) == 3 and img.shape[2] == 4: AttributeError: 'NoneType' object has no attribute 'shape'

Line 137, which is reading the image using cv2.imread() is getting null value. It should be an numpy array (like these: (612, 402, 3) ), for any RGB image. Try to check whether you are passing the right path/correct file of input images in the terminal argument.

**Comment by sampanes** [comment]
I'm getting this same error after running the command:

`python inference_realesrgan.py -n RealESRGAN_x4plus_anime_6B -i inputs`

for the second time, first time I ran it I got torchvision.transofmrs.functional_tensor not found, another thread told me to add an underscore and that worked.

so IDK about it being a path to images if I did not specify images, it should be whatever comes with the repo right?

full output:

```
Downloading: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth" to C:\Users\John\Documents\video2x\shangar21_stuff\Real-ESRGAN\weights\RealESRGAN_x4plus_anime_6B.pth

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17.1M/17.1M [00:01<00:00, 17.5MB/s] 
Testing 0 00003
Testing 1 00017_gray
Testing 2 0014
Testing 3 0030
Testing 4 ADE_val_00000114
Testing 5 OST_009
Testing 6 children-alpha
Testing 7 tree_alpha_16bit
        Input is a 16-bit image
Testing 8 video
[ WARN:0@26275.641] global loadsave.cpp:248 cv::findDecoder imread_('inputs\video'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\John\Documents\video2x\shangar21_stuff\Real-ESRGAN\inference_realesrgan.py", line 166, in <module>
    main()
  File "C:\Users\John\Documents\video2x\shangar21_stuff\Real-ESRGAN\inference_realesrgan.py", line 138, in main
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'
```
