### ISSUE TITLE
Loading RealESRNet_x4plus.pth - RealESRGAN Training bug

### ISSUE THREAD

**Issue by House-Leo** [xinntao/Real-ESRGAN#82]
```python
2021-09-17 11:46:08,530 INFO: Loading RRDBNet model from experiments/pretrained_models/RealESRNet_x4plus.pth.
Traceback (most recent call last):
  File "realesrgan/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/train.py", line 128, in train_pipeline
    model = build_model(opt)
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/home/yzj6850/houselee/Real-ESRGAN/realesrgan/models/realesrgan_model.py", line 19, in __init__
    super(RealESRGANModel, self).__init__(opt)
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/sr_model.py", line 29, in __init__
    self.load_network(self.net_g, load_path, self.opt['path'].get('strict_load_g', True))
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/base_model.py", line 270, in load_network
    load_net = load_net[param_key]
KeyError: 'params'
```

**Comment by House-Leo** [comment]
But when I tried to load the RealESRNet pre-model I trained it works fine.
```python
2021-09-17 14:17:10,795 INFO: Loading RRDBNet model from /home/yzj6850/houselee/Real-ESRGAN/experiments/RealESRNet/models/net_g_80000.pth.
2021-09-17 14:17:11,086 INFO: Use Exponential Moving Average with decay: 0.999
2021-09-17 14:17:11,426 INFO: Network [RRDBNet] is created.
2021-09-17 14:17:11,490 INFO: Loading RRDBNet model from /home/yzj6850/houselee/Real-ESRGAN/experiments/NTIRE_RealESRNet/models/net_g_80000.pth.
```
I found that the model I trained is about 127MB, but the model you provided is about 64MB. 

Look forward to your answer. Thanks!

**Comment by xinntao** [comment]
Try to set `param_key_g: params_ema` in your option file, just like the example:
https://github.com/xinntao/Real-ESRGAN/blob/aa584e05bcc8eed89cf4a9835a842f6c9918f33c/options/finetune_realesrgan_x4plus.yml#L100-L106

The pth file has saved two sets of parameters：
1. `params`: for the original parameters
2. `params_ema`: for the EMA parameters

When I publish the model, I only keep the `params_ema` for better performance.

So, in the fine-tuning, you may need to set the param_key_g: params_ema` option.

**Comment by House-Leo** [comment]
> Try to set `param_key_g: params_ema` in your option file, just like the example:
> https://github.com/xinntao/Real-ESRGAN/blob/aa584e05bcc8eed89cf4a9835a842f6c9918f33c/options/finetune_realesrgan_x4plus.yml#L100-L106
> 
> The pth file has saved two sets of parameters：
> 
> 1. `params`: for the original parameters
> 2. `params_ema`: for the EMA parameters
> 
> When I publish the model, I only keep the `params_ema` for better performance.
> 
> So, in the fine-tuning, you may need to set the param_key_g: params_ema` option.

```
Version Information: 
	BasicSR: 1.3.3.10
	PyTorch: 1.7.1
	TorchVision: 0.8.2
2021-09-17 16:32:44,997 INFO: 
  name: debug_finetune_RealESRGANx4plus_ntire
  model_type: RealESRGANModel
  scale: 4
  num_gpu: 3
  manual_seed: 0
  l1_gt_usm: True
  percep_gt_usm: True
  gan_gt_usm: False
  resize_prob: [0.2, 0.7, 0.1]
  resize_range: [0.15, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 30]
  poisson_scale_range: [0.05, 3]
  gray_noise_prob: 0.4
  jpeg_range: [30, 95]
  second_blur_prob: 0.8
  resize_prob2: [0.3, 0.4, 0.3]
  resize_range2: [0.3, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 25]
  poisson_scale_range2: [0.05, 2.5]
  gray_noise_prob2: 0.4
  jpeg_range2: [30, 95]
  gt_size: 256
  queue_size: 180
  datasets:[
    train:[
      name: DF2K+OST
      type: RealESRGANDataset
      dataroot_gt: /home/yzj6850/houselee/dataset/ntire2020
      meta_info: /home/yzj6850/houselee/dataset/ntire2020/meta_info/meta_info_DF2Kmultiscale.txt
      io_backend:[
        type: disk
      ]
      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob: 0.1
      blur_sigma: [0.2, 3]
      betag_range: [0.5, 4]
      betap_range: [1, 2]
      blur_kernel_size2: 21
      kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob2: 0.1
      blur_sigma2: [0.2, 1.5]
      betag_range2: [0.5, 4]
      betap_range2: [1, 2]
      final_sinc_prob: 0.8
      gt_size: 256
      use_hflip: True
      use_rot: False
      use_shuffle: True
      num_worker_per_gpu: 5
      batch_size_per_gpu: 12
      dataset_enlarge_ratio: 1
      prefetch_mode: None
      phase: train
      scale: 4
    ]
    val:[
      name: validation
      type: PairedImageDataset
      dataroot_gt: /home/yzj6850/houselee/dataset/df2k/DIV2K_valid_HR
      dataroot_lq: /home/yzj6850/houselee/dataset/ntire2020/track1-valid-input
      io_backend:[
        type: disk
      ]
      phase: val
      scale: 4
    ]
  ]
  network_g:[
    type: RRDBNet
    num_in_ch: 3
    num_out_ch: 3
    num_feat: 64
    num_block: 23
    num_grow_ch: 32
  ]
  network_d:[
    type: UNetDiscriminatorSN
    num_in_ch: 3
    num_feat: 64
    skip_connection: True
  ]
  path:[
    pretrain_network_g: experiments/pretrained_models/RealESRNet_x4plus.pth
    param_key_g: params_ema
    strict_load_g: True
    pretrain_network_d: experiments/pretrained_models/RealESRGAN_x4plus_netD.pth
    param_key_d: params
    strict_load_d: True
    resume_state: None
    experiments_root: /home/yzj6850/houselee/Real-ESRGAN/experiments/debug_finetune_RealESRGANx4plus_ntire
    models: /home/yzj6850/houselee/Real-ESRGAN/experiments/debug_finetune_RealESRGANx4plus_ntire/models
    training_states: /home/yzj6850/houselee/Real-ESRGAN/experiments/debug_finetune_RealESRGANx4plus_ntire/training_states
    log: /home/yzj6850/houselee/Real-ESRGAN/experiments/debug_finetune_RealESRGANx4plus_ntire
    visualization: /home/yzj6850/houselee/Real-ESRGAN/experiments/debug_finetune_RealESRGANx4plus_ntire/visualization
  ]
  train:[
    ema_decay: 0.999
    optim_g:[
      type: Adam
      lr: 0.0001
      weight_decay: 0
      betas: [0.9, 0.99]
    ]
    optim_d:[
      type: Adam
      lr: 0.0001
      weight_decay: 0
      betas: [0.9, 0.99]
    ]
    scheduler:[
      type: MultiStepLR
      milestones: [400000]
      gamma: 0.5
    ]
    total_iter: 400000
    warmup_iter: -1
    pixel_opt:[
      type: L1Loss
      loss_weight: 1.0
      reduction: mean
    ]
    perceptual_opt:[
      type: PerceptualLoss
      layer_weights:[
        conv1_2: 0.1
        conv2_2: 0.1
        conv3_4: 1
        conv4_4: 1
        conv5_4: 1
      ]
      vgg_type: vgg19
      use_input_norm: True
      perceptual_weight: 1.0
      style_weight: 0
      range_norm: False
      criterion: l1
    ]
    gan_opt:[
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      loss_weight: 0.1
    ]
    net_d_iters: 1
    net_d_init_iters: 0
  ]
  val:[
    val_freq: 8
    save_img: True
    metrics:[
      psnr:[
        type: calculate_psnr
        crop_border: 4
        test_y_channel: False
      ]
    ]
  ]
  logger:[
    print_freq: 1
    save_checkpoint_freq: 8
    use_tb_logger: True
    wandb:[
      project: None
      resume_id: None
    ]
  ]
  dist_params:[
    backend: nccl
    port: 29500
  ]
  is_train: True
  auto_resume: False
  dist: True
  rank: 0
  world_size: 3
  root_path: /home/yzj6850/houselee/Real-ESRGAN

2021-09-17 16:32:45,019 INFO: Dataset [RealESRGANDataset] - DF2K+OST is built.
2021-09-17 16:32:45,020 INFO: Training statistics:
	Number of train images: 17250
	Dataset enlarge ratio: 1
	Batch size per gpu: 12
	World size (gpu number): 3
	Require iter number per epoch: 480
	Total epochs: 834; iters: 400000.
2021-09-17 16:32:45,023 INFO: Dataset [PairedImageDataset] - validation is built.
2021-09-17 16:32:45,023 INFO: Number of val images/folders in validation: 100
2021-09-17 16:32:45,406 INFO: Network [RRDBNet] is created.
2021-09-17 16:32:45,574 INFO: Network: DistributedDataParallel - RRDBNet, with parameters: 16,697,987
2021-09-17 16:32:45,592 INFO: Loading RRDBNet model from experiments/pretrained_models/RealESRNet_x4plus.pth.

Traceback (most recent call last):
  File "realesrgan/train.py", line 11, in <module>
Traceback (most recent call last):
  File "realesrgan/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/train.py", line 128, in train_pipeline
    model = build_model(opt)    train_pipeline(root_path)

  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/train.py", line 128, in train_pipeline
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/home/yzj6850/houselee/Real-ESRGAN/realesrgan/models/realesrgan_model.py", line 19, in __init__
    model = build_model(opt)
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/__init__.py", line 27, in build_model
    super(RealESRGANModel, self).__init__(opt)
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/sr_model.py", line 29, in __init__
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/home/yzj6850/houselee/Real-ESRGAN/realesrgan/models/realesrgan_model.py", line 19, in __init__
    self.load_network(self.net_g, load_path, self.opt['path'].get('strict_load_g', True))
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/base_model.py", line 270, in load_network
    super(RealESRGANModel, self).__init__(opt)
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/sr_model.py", line 29, in __init__
    self.load_network(self.net_g, load_path, self.opt['path'].get('strict_load_g', True))
  File "/home/yzj6850/.conda/envs/basicsr/lib/python3.7/site-packages/basicsr/models/base_model.py", line 270, in load_network
    load_net = load_net[param_key]
KeyError: 'params'
```

Got the same error after I set the `param_key_g: params_ema`

**Comment by House-Leo** [comment]
> Try to set `param_key_g: params_ema` in your option file, just like the example:
> https://github.com/xinntao/Real-ESRGAN/blob/aa584e05bcc8eed89cf4a9835a842f6c9918f33c/options/finetune_realesrgan_x4plus.yml#L100-L106
> 
> The pth file has saved two sets of parameters：
> 
> 1. `params`: for the original parameters
> 2. `params_ema`: for the EMA parameters
> 
> When I publish the model, I only keep the `params_ema` for better performance.
> 
> So, in the fine-tuning, you may need to set the param_key_g: params_ema` option.

I just updated basicsr version to 1.3.4.2, and it works fine now. Thanks for your help.

**Comment by darvida** [comment]
I have the same problem, how did you fix it ?
