### ISSUE TITLE
 local variable 'file_url' referenced before assignment

### ISSUE THREAD

**Issue by Kaiser42** [xinntao/Real-ESRGAN#833]
Traceback (most recent call last):
  File "C:\Users\Kaiser\Documents\GitHub\manga-colorization-GUI\realesrgan\inference_realesrgan.py", line 166, in <module>
    main()
  File "C:\Users\Kaiser\Documents\GitHub\manga-colorization-GUI\realesrgan\inference_realesrgan.py", line 94, in main
    for url in file_url:
UnboundLocalError: local variable 'file_url' referenced before assignment

**Comment by Kaiser42** [comment]
Even changing the names to the correct ones does not work.
![image](https://github.com/user-attachments/assets/d4ffcee7-1ab7-43f8-a1ae-5eb56ce86975)
