### ISSUE TITLE
No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by purgenetik** [xinntao/Real-ESRGAN#841]
This error is generated trying to run colab demo (step 3)
https://colab.research.google.com/drive/1k2Zod6kSHEvraybHl50Lys0LerhyTMCo?usp=sharing

and any other code attempts give the same error
Any ideas how to fix it?

Traceback (most recent call last):
  File "/content/Real-ESRGAN/inference_realesrgan.py", line 5, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

**Comment by WallaceCCWong** [comment]
edit file "degradation.py"  line 8 from:
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
to:
    from torchvision.transforms._functional_tensor import rgb_to_grayscale

**Comment by VATHIAR** [comment]
for anyone found it difficult to find the file,

```
# Path to the file
file_path = '/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py'

# Open the file, read its contents, and replace the desired line
with open(file_path, 'r') as file:
    code = file.read()

# Replace the import line
modified_code = code.replace(
    "from torchvision.transforms.functional_tensor import rgb_to_grayscale",
    "from torchvision.transforms._functional_tensor import rgb_to_grayscale"
)

# Write the modified code back to the file
with open(file_path, 'w') as file:
    file.write(modified_code)
```

**Comment by amrakm** [comment]
or downgrade your torchvision to `=0.14.1`

**Comment by h3clikejava** [comment]
After change:
ModuleNotFoundError: No module named 'realesrgan.version'
